/**
 * build-models-catalog.ts
 *
 * Generates `src/lib/agent/llm/catalog-bundled.ts` — an offline-primary,
 * self-contained model catalog — from the downloaded models.dev dataset
 * (TOML source of truth) at /Users/wasd/Downloads/models.dev-dev.
 *
 * Run: `npx tsx scripts/build-models-catalog.ts`
 *
 * The dataset layout consumed here:
 *   providers/<pid>/provider.toml            -> provider metadata (name, env, npm, api, doc)
 *   providers/<pid>/models/ (recursively, *.toml) -> per-model serving metadata
 *
 * Model-id derivation (important):
 *   - Use `base_model` when present, else the path relative to `models/` (minus
 *     `.toml`, slashes preserved).
 *   - If the id's leading namespace equals the provider dir (first-party, e.g.
 *     `anthropic/claude-haiku-4-5`), strip the namespace to a BARE slug
 *     (`claude-haiku-4-5`) — that is what the real provider API and the
 *     extension's `DEFAULT_MODELS` expect.
 *   - If the id is namespaced to a DIFFERENT provider (aggregator such as
 *     openrouter, whose `base_model` points at an upstream vendor), keep it
 *     NAMESPACED, then strip a trailing date (`-20241022` / `-2024-08-06`) and
 *     dotify version numbers (`3-5` -> `3.5`). This produces the dotted,
 *     un-dated OpenRouter id the extension uses, e.g.
 *     `anthropic/claude-3-5-sonnet-20241022` -> `anthropic/claude-3.5-sonnet`.
 *
 * Date resolution:
 *   - Prefer the model's own `release_date`, else `last_updated`.
 *   - Fall back to a cross-provider lookup: an aggregator model keyed by its
 *     bare slug inherits the date published in the upstream (first-party)
 *     model file, when that file has one.
 *   - Otherwise default to `1970-01-01` (a known dataset quirk: many
 *     anthropic/openrouter model files omit any date field).
 */

import {
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "smol-toml";

const DATASET_ROOT = "/Users/wasd/Downloads/models.dev-dev";
const PROVIDERS_DIR = join(DATASET_ROOT, "providers");

const HEADER =
  "/* AUTO-GENERATED by scripts/build-models-catalog.ts — do not edit by hand. " +
  "Regenerate from the models.dev dataset. */\n";

const DEFAULT_DATE = "1970-01-01";

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function walk(dir: string): string[] {
  const out: string[] = [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const name of entries) {
    const full = join(dir, name);
    let st;
    try {
      st = statSync(full);
    } catch {
      // Broken symlink or unreadable entry — skip it.
      continue;
    }
    if (st.isDirectory()) out.push(...walk(full));
    else if (name.endsWith(".toml")) out.push(full);
  }
  return out;
}

/** Parse a number that may use TOML underscore separators (e.g. `400_000`). */
function parseNum(v: unknown): number | undefined {
  if (typeof v === "number") return v;
  if (typeof v === "string") {
    const n = Number(v.replace(/_/g, ""));
    return Number.isFinite(n) ? n : undefined;
  }
  return undefined;
}

/** Normalize a date-ish value to `YYYY-MM-DD` (defaulting when absent/malformed). */
function normalizeDate(v: unknown): string {
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  if (typeof v !== "string") return DEFAULT_DATE;
  const s = v.trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  if (/^\d{4}-\d{2}$/.test(s)) return `${s}-01`;
  if (/^\d{4}$/.test(s)) return `${s}-01-01`;
  // tolerate a full timestamp
  const m = s.match(/^(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : DEFAULT_DATE;
}

/** Strip a trailing date suffix: `-YYYYMMDD` or `-YYYY-MM-DD`. */
function stripTrailingDate(s: string): string {
  return s.replace(/-\d{8}$/, "").replace(/-\d{4}-\d{2}-\d{2}$/, "");
}

/** Dotify a standalone `X-Y` version number (e.g. `3-5` -> `3.5`), but NOT a
 *  size suffix like `8b` (guarded by the negative lookahead for a letter). */
function dotifyVersion(s: string): string {
  return s.replace(/(\d+)-(\d+)(?![a-zA-Z])/g, "$1.$2");
}

/** Bare slug used for cross-provider date lookup: strip namespace + trailing date. */
function bareSlugForDate(rawId: string): string {
  const noNs = rawId.includes("/") ? rawId.slice(rawId.indexOf("/") + 1) : rawId;
  return stripTrailingDate(noNs);
}

/** Compute the final catalog model id. */
function deriveId(providerId: string, baseModel: string | undefined, pathId: string): string {
  const raw = baseModel ?? pathId;
  const slash = raw.indexOf("/");
  const ns = slash >= 0 ? raw.slice(0, slash) : "";
  if (ns && ns === providerId) {
    // First-party model: bare slug, kept exactly as the source (hyphenated,
    // dated ids preserved — matches the real provider API + DEFAULT_MODELS).
    return raw.slice(slash + 1);
  }
  // Aggregator (or namespace differs): namespaced, un-dated, dotted version.
  return dotifyVersion(stripTrailingDate(raw));
}

// ---------------------------------------------------------------------------
// parse provider + model metadata
// ---------------------------------------------------------------------------

interface RawModel {
  providerId: string;
  candidateId: string;
  dateLookupKey: string;
  baseModel?: string;
  pathId: string;
  toml: Record<string, any>;
}

function parseProviderToml(pid: string): {
  name: string;
  env?: string[];
  npm?: string;
  api?: string;
  doc?: string;
} {
  const p = join(PROVIDERS_DIR, pid, "provider.toml");
  let raw: Record<string, any> = {};
  try {
    raw = parse(readFileSync(p, "utf8")) as Record<string, any>;
  } catch {
    raw = {};
  }
  const meta: { name: string; env?: string[]; npm?: string; api?: string; doc?: string } = {
    name: typeof raw.name === "string" ? raw.name : pid,
  };
  if (Array.isArray(raw.env)) meta.env = raw.env.filter((x: unknown) => typeof x === "string");
  if (typeof raw.npm === "string") meta.npm = raw.npm;
  if (typeof raw.api === "string") meta.api = raw.api;
  if (typeof raw.doc === "string") meta.doc = raw.doc;
  return meta;
}

function collectModels(): { raw: RawModel[]; dateBySlug: Map<string, { release_date?: string; last_updated?: string }> } {
  const raw: RawModel[] = [];
  const dateBySlug = new Map<string, { release_date?: string; last_updated?: string }>();

  const providerDirs = readdirSync(PROVIDERS_DIR).filter((d) =>
    statSync(join(PROVIDERS_DIR, d)).isDirectory(),
  );

  for (const pid of providerDirs) {
    const modelsDir = join(PROVIDERS_DIR, pid, "models");
    const files = walk(modelsDir);
    for (const file of files) {
      let toml: Record<string, any> = {};
      try {
        toml = parse(readFileSync(file, "utf8")) as Record<string, any>;
      } catch {
        continue;
      }
      const rel = file.slice(modelsDir.length + 1).replace(/\.toml$/, "");
      const pathId = rel; // relative to models/, slashes preserved
      const baseModel = typeof toml.base_model === "string" ? toml.base_model : undefined;
      const candidateId = deriveId(pid, baseModel, pathId);
      const dateLookupKey = bareSlugForDate(baseModel ?? pathId);
      raw.push({ providerId: pid, candidateId, dateLookupKey, baseModel, pathId, toml });

      // Populate cross-provider date lookup from any file that carries a date.
      const rd = toml.release_date;
      const lu = toml.last_updated;
      if (rd || lu) {
        const existing = dateBySlug.get(dateLookupKey);
        // Prefer an entry that has release_date; otherwise keep whatever we have.
        if (!existing || (rd && !existing.release_date)) {
          dateBySlug.set(dateLookupKey, {
            release_date: rd ? normalizeDate(rd) : existing?.release_date,
            last_updated: lu ? normalizeDate(lu) : existing?.last_updated,
          });
        }
      }
    }
  }
  return { raw, dateBySlug };
}

// ---------------------------------------------------------------------------
// build CatalogModel objects
// ---------------------------------------------------------------------------

function buildModel(m: RawModel, dateBySlug: Map<string, { release_date?: string; last_updated?: string }>, maxDesc: number): Record<string, any> {
  const t = m.toml;
  const out: Record<string, any> = {};

  out.id = m.candidateId;
  out.name = typeof t.name === "string" ? t.name : m.baseModel ?? m.pathId;

  // release_date resolution
  let rel = t.release_date ? normalizeDate(t.release_date) : undefined;
  let upd = t.last_updated ? normalizeDate(t.last_updated) : undefined;
  if (!rel && !upd) {
    const fromLookup = dateBySlug.get(m.dateLookupKey);
    if (fromLookup) {
      rel = fromLookup.release_date;
      upd = fromLookup.last_updated;
    }
  }
  out.release_date = rel ?? upd ?? DEFAULT_DATE;

  if (typeof t.family === "string") out.family = t.family;
  if (typeof t.description === "string") {
    const d = t.description.replace(/\s+/g, " ").trim();
    out.description = d.length > maxDesc ? d.slice(0, maxDesc).trimEnd() + "…" : d;
  }

  out.attachment = t.attachment === true;
  out.reasoning = t.reasoning === true;
  out.temperature = t.temperature === true;
  out.tool_call = t.tool_call === true;

  // modalities
  if (t.modalities && typeof t.modalities === "object") {
    const mod: { input?: string[]; output?: string[] } = {};
    if (Array.isArray(t.modalities.input)) mod.input = t.modalities.input.filter((x: unknown) => typeof x === "string");
    if (Array.isArray(t.modalities.output)) mod.output = t.modalities.output.filter((x: unknown) => typeof x === "string");
    if (mod.input || mod.output) out.modalities = mod;
  }

  // limit
  if (t.limit && typeof t.limit === "object") {
    const ctx = parseNum(t.limit.context);
    const outLim = parseNum(t.limit.output);
    if (ctx !== undefined && outLim !== undefined) {
      const lim: { context: number; output: number; input?: number } = { context: ctx, output: outLim };
      const inLim = parseNum(t.limit.input);
      if (inLim !== undefined) lim.input = inLim;
      out.limit = lim;
    }
  }

  // cost (use the base [cost] table; tiers are volume overrides, ignored)
  if (t.cost && typeof t.cost === "object") {
    const ci = parseNum(t.cost.input);
    const co = parseNum(t.cost.output);
    if (ci !== undefined && co !== undefined) {
      const cost: { input: number; output: number; cache_read?: number; cache_write?: number } = {
        input: ci,
        output: co,
      };
      const cr = parseNum(t.cost.cache_read);
      if (cr !== undefined) cost.cache_read = cr;
      const cw = parseNum(t.cost.cache_write);
      if (cw !== undefined) cost.cache_write = cw;
      out.cost = cost;
    }
  }

  // status — surface deprecation (and maturity) flags verbatim
  if (typeof t.status === "string") out.status = t.status;

  return out;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

function buildCatalog(maxDesc: number) {
  const { raw, dateBySlug } = collectModels();

  const catalog: Record<string, any> = {};

  // provider metadata
  const providerIds = Array.from(new Set(raw.map((m) => m.providerId))).sort();
  for (const pid of providerIds) {
    const meta = parseProviderToml(pid);
    catalog[pid] = { ...meta, id: pid, models: {} };
  }

  // models (dedupe by id within a provider; keep the entry with a real date)
  for (const m of raw) {
    const provider = catalog[m.providerId];
    if (!provider) continue;
    const built = buildModel(m, dateBySlug, maxDesc);
    const existing = provider.models[built.id];
    if (!existing) {
      provider.models[built.id] = built;
    } else if (existing.release_date === DEFAULT_DATE && built.release_date !== DEFAULT_DATE) {
      provider.models[built.id] = built;
    }
  }

  return catalog;
}

function main() {
  const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "lib", "agent", "llm", "catalog-bundled.ts");
  mkdirSync(dirname(outPath), { recursive: true });

  let maxDesc = 240;
  let catalog = buildCatalog(maxDesc);
  let json = JSON.stringify(catalog, null, 2);
  let size = Buffer.byteLength(json, "utf8");

  // Trim descriptions further if the file is too large to keep the bundle lean.
  if (size > 2.5 * 1024 * 1024 && maxDesc > 160) {
    maxDesc = 160;
    catalog = buildCatalog(maxDesc);
    json = JSON.stringify(catalog, null, 2);
    size = Buffer.byteLength(json, "utf8");
  }

  const content = HEADER + 'import type { Catalog } from "./catalog";\n\n' +
    "export const BUNDLED_CATALOG: Catalog = " + json + ";\n";

  writeFileSync(outPath, content, "utf8");

  // Report
  const providers = Object.keys(catalog).length;
  let models = 0;
  for (const p of Object.values(catalog) as any[]) models += Object.keys(p.models).length;
  console.log(`Wrote ${outPath}`);
  console.log(`Providers: ${providers}`);
  console.log(`Models:    ${models}`);
  console.log(`File size: ${(size / 1024 / 1024).toFixed(2)} MB (description cap ${maxDesc} chars)`);
}

main();
